### ISSUE TITLE
Doesn't work with scenery outside FG_HOME (2017.3.0)

### ISSUE THREAD

**Issue by HHS81** [thomass171/GroundServices#1]
Doesn't work with 2017.3.0 and with that with upcoming stable Release 2017.3.1.
win 8.1 64bit 

Tested with Release 2.0 just today:

Error message right after starting FGFS: 
`Nasal runtime error: undefined symbol: logger
  at C:/Users/Heiko/FlightGear/GIT/flightgear-fgdata/Nasal/groundservices/main.n
as, line 67
  called from: C:/Users/Heiko/FlightGear/GIT/flightgear-fgdata/Nasal/groundservi
ces/main.nas, line 86
  called from: C:/Users/Heiko/FlightGear/GIT/flightgear-fgdata/Nasal/groundservi
ces/main.nas, line 349
  called from: C:/Users/Heiko/FlightGear/GIT/flightgear-fgdata/Nasal/groundservi
ces/main.nas, line 157
  called from: C:/Users/Heiko/FlightGear/GIT/flightgear-fgdata/Nasal/groundservi
ces/main.nas, line 161`

The nasal log file lists following:
`20:50:05 DEBUG executing Graph.nas
20:50:05 DEBUG completed Graph.nas
20:50:05 DEBUG executing GraphUtils.nas
20:50:05 DEBUG completed GraphUtils.nas
20:50:05 DEBUG executing GroundServiceVisualizer.nas
20:50:05 DEBUG completed GroundServiceVisualizer.nas
20:50:05 DEBUG executing GroundVehicle.nas
20:50:05 DEBUG completed GroundVehicle.nas
20:50:05 DEBUG executing Groundnet.nas
20:50:05 DEBUG completed Groundnet.nas
20:50:05 DEBUG executing main.nas
20:50:05 DEBUG completed main.nas
20:50:05 DEBUG executing maintest.nas
20:50:05 DEBUG completed maintest.nas
20:50:05 DEBUG executing mathutil.nas
20:50:05 DEBUG completed mathutil.nas
20:50:05 DEBUG executing util.nas
20:50:05 DEBUG completed util.nas
20:50:05 DEBUG main: module groundservices loaded
20:50:05 DEBUG reinit
20:50:05 DEBUG Airports within 3 nm: Koln Bonn (EDDK),
20:50:05 DEBUG Found airport Koln Bonn (EDDK,lat/lon=50.86538774008813;7.139103876651988,ele=92.04959999999999 m)
20:50:05 DEBUG center: lat=50.86538774008813,lon=7.139103876651988
20:50:05 WARN  no altitide from geodinfo(50.86538774008813,7.139103876651988). Using airportelevation 92.04959999999999 m
20:50:05 DEBUG ignoring airport. No elevation info
20:50:27 DEBUG Airports within 3 nm: Koln Bonn (EDDK),
20:50:27 DEBUG Found airport Koln Bonn (EDDK,lat/lon=50.86538774008813;7.139103876651988,ele=92.04959999999999 m)
20:50:27 DEBUG center: lat=50.86538774008813,lon=7.139103876651988
20:50:27 DEBUG Looking for groundnet in C:/Users/Heiko/AppData/Roaming/flightgear.org/TerraSync/Airports/E/D/D/EDDK.groundnet.xml
20:50:27 ERROR Reading failed :C:/Users/Heiko/AppData/Roaming/flightgear.org/TerraSync/Airports/E/D/D/EDDK.groundnet.xml
20:50:27 ERROR no groundnet for airport EDDK. Added to ignorelist`

Please notice, that TerraSync can be placed everywhere by the user and and not only in $FG_Home (aka  AppDate/Roaming/flightgear.org on win)
I have selected a different place for TerraSync on my system

**Comment by HHS81** [comment]
Adding the Terrasync-folders to §FG_Home let the error-messages disappear and I can see moving vehicles at EDDK.

That means the system here needs a fixed place for the groundnet.xmls and doesn't rely on FlightGear flexibility.

**Comment by thomass171** [comment]
1) There is a typo "logger" in main.nas, which only is reached in case of airport not found.
2) The above description applies. groundnet.xml is looked for only in FG_HOME currently.
Will fix 1) and look for a solution for 2).

**Comment by thomass171** [comment]
Fixed in Code. Now the groundnet.xml is looked for along the FG_SCENERY path.
