### ISSUE TITLE
Error message, GroundServices not working

### ISSUE THREAD

**Issue by HHS81** [thomass171/GroundServices#3]
Error message when Show Status selected: `Nasal runtime error: undefined symbol: groundservices
  at __dlg:groundservices, line 43
Nasal runtime error: undefined symbol: groundservices
  at /sim/bindings/gui/binding[12], line 1`

Also greyed out vehicle and Aircraft select dialog.

Tested with FlightGear 2017.4.0, installed as Addon `(--addon=/C:/Users/hhs81/FlightGear/addons/GroundServices)`, LOCATIONOFADDON/gui/dialogs/groundservices.xml copied to $FG_ROOT/gui/dialogs

**Comment by thomass171** [comment]
The Nasal runtime error message occurs, when the addon wasn't installed. I can reproduce it by starting FG without the addon option for loading the addon. Unfortunately the menu item AI->GroundServices is still available even if the addon wasn't loaded.

Could you please check whether the error also occurs when the FG log contains a success message for loading the addon like

```
Initializing addon from C:/Users/thomass/Documents/Flusi/addons/GroundServices/main.nas in __addon[0]__
GroundServices addon initialized from pathC:/Users/thomass/Documents/Flusi/addons/GroundServices
```

**Comment by HHS81** [comment]
@thomass171 
I don't get the addon working (well, any of the available addon isn't working, though they appear in the property browser.) So no success message.

Which is your command line to get the addon working?

**Comment by thomass171** [comment]
The command lines I use for starting FG are for MacOS:

fgfs --fg-root=/Users/thomass/Flusi/FlightGear-2017.3.1/Resources/data --lat=50.876611 --lon=7.128904
 --altitude=450 --heading=285 --pitch=25 --console --log-level=debug --aircraft=ufo --enable-auto-coordination 
 --prop:/controls/gear/brake-parking=1 --timeofday=noon --prop:/sim/terrasync/svn-data-server=http://ns334561.ip-5-196-65.eu:8888/trunk/data/Scenery 
 --prop:string:/sim/terrasync/enabled=true --generic=socket,out,3,255.255.255.255,5700,udp,flightgear-outdata-FG737-gen 
 --telnet=5702 --httpd=5701 --disable-real-weather-fetch --addon=/Users/thomass/Flusi/addons/ModelCockpitView 
 --addon=/Users/thomass/Flusi/addons/Skeleton --addon=/Users/thomass/Flusi/addons/GroundServices
 
and Windows:

 "C:\Program Files\FlightGear 2017.3.1\bin\fgfs.exe"  --fg-root="C:\Program Files\FlightGear 2017.3.1\data" --airport=EDDF --timeofday=noon --aircraft=747-400 --parkpos=B44 --httpd=5701 --addon=C:\Users\thomass\Documents\Flusi\addons\GroundServices

**Comment by HHS81** [comment]
Thanks!
Obviously I got the slashes wrong.

Nethertheless, follwoing new error message appear: `Nasal runtime error: No such member: registeredAddons
  at C:/Users/Heiko/FlightGear/GIT/flightgear-fgdata/Nasal/addons.nas, line 24`

And with this, it isn't all working yet. The issue remain.

I guess my 2017.4.0 is already too old, since there had been some changes to the addon-structure.

**Comment by HHS81** [comment]
I got the other addons working, just not GroundServices - at launch of FGFS I get a message "unable to tegister", addon-metadata.xml is missing here.

**Comment by thomass171** [comment]
I recently noticed activities on the FG developer mailing list for extending the addons interface structure. Apparently additional files are required like metadata.xml. So this addon will not work with latest FG versions (but it does in 2017.3.1). I'll extend the addon.

**Comment by thomass171** [comment]
Release 0.4.0 is available now which complies to the new addon structure.
